 ##### GET Request To Move Between Pages #####

index:
    path: /
    controller: App\Controller\RouteController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

signup:
    path: /signup
    controller: App\Controller\SecurityController::signup

get_login:
    path: /login
    controller: App\Controller\RouteController::index
    methods: [GET]
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

cart:
    path: /cart/{id}
    controller: App\Controller\RouteController::cart

dashboard:
    path: /dashboard
    controller: App\Controller\RouteController::dashboard

categories:
    path: /categories
    controller: App\Controller\RouteController::categories

add_category:
    path: /categories/add
    controller: App\Controller\CategoryController::add

products:
    path: /products
    controller: App\Controller\RouteController::products

add_product:
    path: /products/add
    controller: App\Controller\ProductController::add

sales:
    path: /sales
    controller: App\Controller\RouteController::sales

get_product_price:
    path: /sales/product/{id}/{sale_value}/calculate
    controller: App\Controller\SaleController::calculate
    methods: [GET]
add_sale:
    path: /sales/add
    controller: App\Controller\SaleController::add

delete_sale:
    path: /sales/delete
    controller: App\Controller\SaleController::delete

clients:
    path: /clients
    controller: App\Controller\RouteController::clients

carts:
    path: /carts
    controller: App\Controller\RouteController::carts

add_cart:
    path: /carts/add
    controller: App\Controller\CartController::add

add_to_cart:
    path: /client/cart/{cart_id}/product/{product_id}/add
    controller: App\Controller\ClientController::add_to_cart
    methods: [POST]

update_cart:
    path: /client/cart/update
    controller: App\Controller\ClientController::update_cart

remove_from_cart:
    path: /client/cart/{client_cart_product_id}/remove
    controller: App\Controller\ClientController::remove_from_cart
    methods: [POST]

empty_cart:
    path: /client/{client_id}/cart/{cart_id}/empty
    controller: App\Controller\ClientController::empty_cart
    methods: [POST]

settings:
    path: /settings
    controller: App\Controller\RouteController::settings

 ##### GET Request To Move Between Pages #####